(defpackage :netaddr
  (:use :cl)
  (:export :make-ip-address
           :make-ip-network
           :make-ip-range
           :make-ip-set
           :make-ip-like
           :add
           :add!
           :addnew
           :addnew!
           :apply-mask
           :apply-mask!
           :sub
           :sub!
           :ip=
           :contains?
           :longest-match
           :contiguous?
           :disjoint?
           :subset?
           :superset?
           :ip-equal
           :ip-equalp
           :int
           :str
           :version
           :first-ip
           :last-ip
           :size
           :ip-set-union
           :ip-set-intersection
           :ip-set-difference
           :ip-set-symmetric-difference
           :enable-ip-syntax
           :public?
           :private?
           :reserved?
           :multicast?
           :route-type))
