(in-package :netaddr)

;;;; Set-like predicates between IP-LIKEs, CONTAINS? and SIZE.

(defun subset? (ip-like-1 ip-like-2)
  "Returns T or an IP-LIKE if IP-LIKE-1 is a subset of IP-LIKE-2. This is synonymous with (CONTAINS? IP-LIKE-2 IP-LIKE-1). Otherwise, returns NIL."
  (check-type ip-like-1 ip-like)
  (check-type ip-like-2 ip-like)
  (contains? ip-like-2 ip-like-1))

(defun strict-subset? (ip-like-1 ip-like-2)
  "Returns T or an IP-LIKE if IP-LIKE-1 is a subset and not IP-EQUAL to IP-LIKE-2."
  (check-type ip-like-1 ip-like)
  (check-type ip-like-2 ip-like)
  (and (not (ip= ip-like-1 ip-like-2))
       (subset? ip-like-1 ip-like-2)))

(defun superset? (ip-like-1 ip-like-2)
  "Returns T or an IP-LIKE if IP-LIKE-1 is a superset of IP-LIKE-2. Otherwise, NIL."
  (check-type ip-like-1 ip-like)
  (check-type ip-like-2 ip-like)
  (subset? ip-like-2 ip-like-1))

(defun strict-superset? (ip-like-1 ip-like-2)
  "Returns T or an IP-LIKE if IP-LIKE-1 is a superset of and not IP-EQUAL to IP-LIKE-2. Otherwise, NIL."
  (check-type ip-like-1 ip-like)
  (check-type ip-like-2 ip-like)
  (strict-subset? ip-like-2 ip-like-1))

(defgeneric disjoint? (ip-like-1 ip-like-2)
  (:documentation "Return T if IP-LIKE-1 and IP-LIKE-2 are disjoint, i.e., they share no IP addresses in common.")
  (:method ((i1 ip-address) (i2 ip-address))
    (not (ip= i1 i2)))
  (:method ((p ip-pair) (i ip-address))
    (not (contains? p i)))
  (:method ((i ip-address) (p ip-pair))
    (disjoint? p i))
  (:method ((p1 ip-pair) (p2 ip-pair))
    (or (< (int (last-ip p1))
           (int (first-ip p2)))
        (< (int (last-ip p2))
           (int (first-ip p1)))))
  (:method ((ip-like-1 t) (ip-like-2 t))
    (check-type ip-like-1 ip-like)
    (check-type ip-like-2 ip-like)))

(defgeneric contiguous? (ip-like-1 ip-like-2)
  (:documentation "Returns T if IP-LIKE-1 and IP-LIKE-2 are contiguous, NIL otherwise.")
  (:method ((i1 ip-address) (i2 ip-address))
    (= 1 (abs (- (int i1) (int i2)))))
  (:method ((p ip-pair) (i ip-address))
    (or (= 1 (abs (- (int (first-ip p)) (int i))))
        (= 1 (abs (- (int (last-ip p)) (int i))))))
  (:method ((i ip-address) (p ip-pair))
    (contiguous? p i))
  (:method ((p1 ip-pair) (p2 ip-pair))
    (or (= 1 (abs (- (int (last-ip p1))
                     (int (first-ip p2)))))
        (= 1 (abs (- (int (last-ip p2))
                     (int (first-ip p1)))))))
  (:method ((ip-like-1 t) (ip-like-2 t))
    (check-type ip-like-1 ip-like)
    (check-type ip-like-2 ip-like)))

(defgeneric intersect (ip-like-1 ip-like-2)
  (:method ((ip1 ip-address) (ip2 ip-address))
    (when (ip= ip1 ip2)
      ip1))
  (:method ((ip ip-address) (p ip-pair))
    (when (contains? p ip)
      ip))
  (:method ((p ip-pair) (ip ip-address))
    (intersect ip p))
  (:method ((p1 ip-pair) (p2 ip-pair))
    (cond ((contains? p1 p2) p2)
          ((contains? p2 p1) p1)
          (t nil)))
  (:method ((ip-like-1 t) (ip-like-2 t))
    (check-type ip-like-1 ip-like)
    (check-type ip-like-2 ip-like)))

;; To make CONTAINS? play nice with MEMBER.
(defun in-set? (ip ip-block)
  (contains? ip-block ip))

(defgeneric contains? (ip+ ip-like)
  (:documentation "Returns T or an IP-LIKE if IP+ contains IP-LIKE, NIL otherwise.")
  (:method ((ip1 ip-address) (ip2 ip-address))
    (ip= ip1 ip2))
  (:method ((pair ip-pair) (ip ip-address))
    (and (= (version pair) (version ip))
         (<= (int (first-ip pair)) (int ip) (int (last-ip pair)))))
  (:method ((pair1 ip-pair) (pair2 ip-pair))
    (and (= (version pair1) (version pair2))
         (<= (int (first-ip pair1))
             (int (first-ip pair2))
             (int (last-ip pair2))
             (int (last-ip pair1)))))
  (:method ((ip ip-address) (pair ip-pair))
    (and (= (version ip) (version pair))
         (= (int ip) (int (first-ip pair)) (int (last-ip pair)))))
  (:method ((set ip-set) (ip-like ip-like))
    (car (member ip-like (slot-value set 'set) :test #'in-set?)))
  (:method ((ip+ t) (ip-like t))
    (check-type ip+ ip+)
    (check-type ip-like ip-like)))

(defgeneric size (ip+)
  (:documentation "Returns an INTEGER of the number of IP addresses contained in IP+.")
  (:method ((ip ip-address)) 1)
  (:method ((pair ip-pair))
    (1+ (- (int (last-ip pair))
           (int (first-ip pair)))))
  (:method ((set ip-set))
    (with-slots (set) set
     (reduce #'+ (mapcar #'size set))))
  (:method ((ip+ t))
    (check-type ip+ ip+)))
